// swift-tools-version: 5.6

import PackageDescription

let package = Package(
    name: "MeemawSDK",
    platforms: [
        SupportedPlatform.iOS(.v13),
        SupportedPlatform.macOS(.v11)
    ],
    products: [
        .library(
            name: "MeemawSDK",
            targets: ["MeemawSDK"]),
    ],
    dependencies: [
        .package(url: "https://github.com/argentlabs/web3.swift", from: "1.1.0")
    ],
    targets: [
        .target(
            name: "MeemawSDK",
            dependencies: [.target(name: "Tsslib"), "web3.swift"]),
        .binaryTarget(
            name: "Tsslib",
            path: "./Sources/Tsslib.xcframework") // replace by url & checksum once hosted online generated by github actions
    ]
)
